twist_mux:
  ros__parameters:
    topics:
      teleop:
        topic: /teleop_vel
        timeout: 0.5
        priority: 70

      joystick:
        topic: /cmd_vel_joy
        timeout: 0.5
        priority: 60

      navigation:
        topic: /nav_vel
        timeout: 0.5
        priority: 80

    locks:
      e_stop:
        topic: /emergency_stop
        timeout: 0.0      # 0.0 = lock stays active until explicitly cleared
        priority: 255     # Bloquea todos los demás si está activo
