<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="mr_holo_omni_4w">


    <xacro:property name="dx" value="0.225"/>   <!-- radius body -->
    <xacro:property name="dz" value="0.05"/>

    <xacro:property name="rad_w" value="0.05"/>
    <xacro:property name="le_w" value="0.05"/>

    <xacro:property name="dx1" value="0.25"/>

    <xacro:property name="dy1" value="0.0"/>


    <xacro:property name="th1" value="${pi/2}"/>


    <xacro:property name="alpha1" value="0"/>


    <material name="white">
        <color rgba= "1 1 1 1"/>
    </material>

   <material name="red">
        <color rgba= "1 0 0 1"/>
    </material>

    <!-- Example link -->
    <link name="base_link">
    </link>
    
    <link name="chassis">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${dx}" length="${dz}"/>
            </geometry>   
            <material name="white">
                <color rgba= "1 1 1 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${dx}" length="${dz}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="base_link_chassis_joint" type="fixed">
        <parent link="base_link"/>
        <child link="chassis"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>

    <link name="w1">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>   
            <material name="black">
                <color rgba= "0 0 0.2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="chassis_w1_joint" type="continuous">
        <parent link="chassis"/>
        <child link="w1"/>
        <origin xyz="${dx1+le_w/2} 0 0" rpy="${th1} 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>

    <link name="w1">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>   
            <material name="black">
                <color rgba= "0 0 0.2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="chassis_w1_joint" type="continuous">
        <parent link="chassis"/>
        <child link="w1"/>
        <origin xyz="${dx1+le_w/2} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>


    <link name="w2">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>   
            <material name="black">
                <color rgba= "0 0 0.2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="chassis_w2_joint" type="continuous">
        <parent link="chassis"/>
        <child link="w2"/>
        <origin xyz="0 ${dx1+le_w/2} 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>

    <link name="w3">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>   
            <material name="black">
                <color rgba= "0 0 0.2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="chassis_w3_joint" type="continuous">
        <parent link="chassis"/>
        <child link="w3"/>
        <origin xyz="${-(dx1+le_w/2)} 0 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>

    <link name="w4">
        <visual>
            <origin xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>   
            <material name="black">
                <color rgba= "0 0 0.2 1"/>
            </material>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${rad_w}" length="${le_w}"/>
            </geometry>
        </collision>
        <inertial>
            <mass value="1"/>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <inertia ixx="1" ixy="1" ixz="1" iyy="1" iyz="1" izz="1"/>
        </inertial>
    </link>

    <joint name="chassis_w4_joint" type="continuous">
        <parent link="chassis"/>
        <child link="w4"/>
        <origin xyz="0 ${-(dx1+le_w/2)} 0" rpy="0 0 0"/>
        <axis xyz="0 0 0"/>    
    </joint>







   
</robot>