joy_node:
  ros__parameters:
    device_id: 0
    deadzone: 0.05
    autorepeat_rate: 20.0

teleop_node:
  ros__parameters:
    axis_linear:
      x: 1
    scale_linear:
      x: 0.5
    axis_linear:
      y: 0
    scale_linear:
      y: 0.5

    axis_angular:
      yaw: 2 # forward right # 2 on logitech and 3 on sony controller
    scale_angular:
      yaw: 2.0
    #axis_angular:
    #  pitch: 4 # forward right # 2 on logitech and 3 on sony controller
    #scale_angular:
    #  pitch: 3.0


    enable_button: 4
    require_enable_button: true